version: "3.8"

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./packwiz:/usr/share/nginx/html/packwiz:ro
      - ./minecraft:/usr/share/nginx/html/minecraft:ro
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "8100:80" # bluemap
      - "25565:25565" # minecraft
    restart: no
    attach: true
    environment:
      TYPE: "FABRIC"
      PACKWIZ_URL: "http://web/packwiz/pack.toml"
      EULA: true
      MOTD: "mya's medieval testing server :3"
      DIFFICULTY: "EASY"
      SEED: "-8302553684957961049"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 6
      OPS_FILE: "http://web/minecraft/ops.json"
      #WHITELIST_FILE: "http://web/minecraft/whitelist.json"
      ENFORCE_WHITELIST: false
      ENABLE_WHITELIST: false
      ONLINE_MODE: true
      MEMORY: "4G"
      USE_AIKAR_FLAGS: true
      VERSION: "1.20.1"
    volumes:
      - ./data:/data
